Iter9
sejo412/ya-metrics pull request #11
Opened 2024-12-21 08:55 UTC by sejo412

2024-12-22 08:34 UTC, zhark0vv requested changes

2024-12-22 08:34 UTC, zhark0vv commented on cmd/agent/app/app.go
> +const maxRand = 10000
```
const (
...
)
```

2024-12-22 08:34 UTC, zhark0vv commented on cmd/server/app/app_test.go
> +				t.Errorf("ParsePostRequestJSON() error = %v, wantErr %v", err, tt.wantErr)
Посмотри в сторону testity и пакетов assert/require для сравнения ожиданий в тестах.

2024-12-22 08:34 UTC, zhark0vv commented on internal/models/models.go
> +const base10 int = 10
const (
...
)

2024-12-22 08:34 UTC, zhark0vv commented on cmd/agent/app/app.go
> +func ReportMetrics(m *Metrics, report *Report, address string, interval, timeout time.Duration, oldAPI bool) {
oldAPI -> isOldAPI

2024-12-22 08:34 UTC, zhark0vv commented on cmd/server/app/app.go
> +func UpdateMetricFromJSON(st Storage, req []byte) ([]byte, error) {
JSON/не JSON лучше разнести по разным файлам.

2024-12-22 08:34 UTC, zhark0vv commented on cmd/server/app/app.go
> +	var metric models.MetricV2
var (
...
)

2024-12-22 08:34 UTC, zhark0vv commented on internal/storage/memory.go
> +func (s *MemoryStorage) Flush(file string) error {
Концептуально в Go, лучше не принимать имя файла на вход, а вместо этого использовать дескрипторы из io.
Например, io.Writer, тогда твоему коду будет безразлично, куда ты пишешь результат.

Пусть решение о том, куда писать примет потребитель, а не Storage.

2024-12-22 08:34 UTC, zhark0vv commented on internal/models/models.go
> +type MetricV2 struct {
Стоит унести весь V2 в отдeльный файл или даже package.

2024-12-22 08:34 UTC, zhark0vv commented on cmd/server/main.go
> +var sugar zap.SugaredLogger
Рекомендую здесь избавиться от глобального состояния логгера.

Смотри, ты используешь Singleton, у тебя есть один глобальный логгер.
Но в Go это антипаттерн. И причин этому две:

- существование концепции поинтеров
- duck-typing
- 
В Go очень хорошо реализуется классический DI, а отсутствие новых объектов гарантируется поинтерами.
Здесь стоит сделать просто обертку, ее конструктор, создать объект логгера в main-пакете и инжетировать ее туда, где она нужна.

Знаю, что так сделано в учебных материалах.
Пример дан для демонстрации. Обычно мы стараемся избегать глобальных зависимостей.

Рекомендую тебе разобраться детальнее с концепцией Dependency Injection и встроить логгер туда, где он нужен явно.

Также его стоит убрать из `main`.

2024-12-22 08:34 UTC, zhark0vv commented on cmd/server/main.go
> +	r.Post("/"+models.MetricPathGetPrefix+"/", getMetricJSON)
Роутинг стоит вынести из main-пакета.
Постарайся сделать main таким компактным, как возможно.
Пусть он создает зависимости, но не определяет их.

2024-12-22 08:34 UTC, zhark0vv commented on cmd/server/handlers_test.go
> +			r := chi.NewRouter()
Лучше не пересоздавать роутер в тестах, а использовать тот, что предоставляет приложение, иначе не тестируется сам маршрут.

2024-12-22 15:37 UTC, sejo412 commented on cmd/agent/app/app.go
> +func ReportMetrics(m *Metrics, report *Report, address string, interval, timeout time.Duration, oldAPI bool) {
здесь не соглашусь.. префикс is обычно используют в проверках на выполнимость тех или иных условий (по моим наблюдениям), а здесь констатация факта. скорей уж useOldApi подходит из контекста. но опять же - чисто вкусовщина. я бы оставил как есть.

2024-12-23 06:19 UTC, zhark0vv approved these changes

2024-12-23 06:19 UTC, zhark0vv commented on internal/storage/memory.go
> +		res, err := models.ConvertV2ToV1(&m)
Единственное замечание - если ты используешь версионирование, доменам стоит быть полностью обособлены и не пересекаться.

2024-12-23 06:20 UTC, zhark0vv commented on cmd/agent/app/app.go
> +func ReportMetrics(m *Metrics, report *Report, address string, interval, timeout time.Duration, oldAPI bool) {
Да, ок, это вкусовщина, не принципиально.

2024-12-23 08:01 UTC, merged