Iter5
sejo412/ya-metrics pull request #6
Opened 2024-11-30 09:55 UTC by sejo412

2024-11-30 15:51 UTC, zhark0vv commented
Большое количество логики в main-packages, рекомендую пересмотреть структуру приложения и добавить сервисные слои, инкапсулирующие бизнес-логику.

2024-11-30 16:08 UTC, zhark0vv requested changes

2024-11-30 16:08 UTC, zhark0vv commented on cmd/agent/app.go
> +func pollMetrics(m *Metrics, c *Config) {
Не обязательно править сейчас, но можно посмотреть в сторону time.Ticker:
https://www.geeksforgeeks.org/time-newticker-function-in-golang-with-examples/

2024-11-30 16:08 UTC, zhark0vv commented on cmd/agent/main_test.go
> +		// TODO: Add test cases.
В тесте нет тест-кейсов?

2024-11-30 16:08 UTC, zhark0vv commented on cmd/agent/main_test.go
> +		// TODO: Add test cases.
Также не добавлены тест-кейсы.

2024-11-30 16:08 UTC, zhark0vv commented on internal/storage/memory.go
> +	Metrics map[string]Metric
Лучше сделать ее приватной.

2024-11-30 16:08 UTC, zhark0vv commented on internal/storage/metrics.go
> +type Metric struct {
Это часть домена, а не storage, лучше перенести в пакет models/domain.

2024-11-30 16:08 UTC, zhark0vv commented on cmd/agent/config.go
> +	"reflect"
Рефлексия - это очень дорого.
Рекомендую попробовать решить задачу без использования этого пакета.

2024-11-30 16:08 UTC, zhark0vv commented on cmd/agent/app.go
> +		ch <- fmt.Sprint(err)
Лучше использовать отдельный канал для ошибок. Именно ошибок, не строк.

2024-11-30 16:08 UTC, zhark0vv commented on internal/config/constants.go
> +	MetricKindGauge      string = "gauge"
Константы не являются частью конфига, они являются частью домена.

2024-11-30 16:08 UTC, zhark0vv commented on internal/storage/metrics.go
> +type Storage interface {
Интерфейсу более Go-way порождать по месту использования, вместо места реализации.

2024-11-30 16:08 UTC, zhark0vv commented on cmd/server/app.go
> +	if r.Method == http.MethodGet {
chi умеет в такое из коробки:

```
r := chi.NewRouter()

	r.Post("/example", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("POST request processed successfully!"))
	})

```

2024-11-30 16:08 UTC, zhark0vv commented on cmd/server/handlers.go
> +var index = `<!DOCTYPE html>
Шаблон лучше вынести в embed-файл.
https://pkg.go.dev/embed

2024-11-30 16:08 UTC, zhark0vv commented on internal/config/errors.go
> +package config
Ошибки тоже часть домена, лучше убрать их из этого пакета.

2024-12-01 07:17 UTC, sejo412 commented on cmd/agent/app.go
> +func pollMetrics(m *Metrics, c *Config) {
да, но в задании:

> Чтобы приостанавливать работу функции на заданное время, используйте вызов time.Sleep(n * time.Second). Подробнее о пакете time и его возможностях вы узнаете в третьем спринте.

2024-12-01 07:57 UTC, sejo412 commented on cmd/server/handlers.go
> +var index = `<!DOCTYPE html>
с embed знаком, но в данном случае не стал его использовать, т.к. шаблон крохотный, embed + html/templates только усложнят логику. считаю нецелесообразным менять в данном случае

2024-12-01 08:04 UTC, zhark0vv commented on cmd/server/handlers.go
> +var index = `<!DOCTYPE html>
Ок, принято. Я в целом предпочитаю не нагружать кодовую базу тем, что к ней не относится, но можно оставить, если это осознанный выбор.

2024-12-01 19:30 UTC, sejo412 commented on cmd/agent/main_test.go
> +		// TODO: Add test cases.
удалил сгенеренные IDE тесты для функций ничего не возвращающих

2024-12-01 19:30 UTC, sejo412 commented on cmd/agent/main_test.go
> +		// TODO: Add test cases.
удалил сгенеренные IDE тесты для функций ничего не возвращающих

2024-12-01 19:30 UTC, sejo412 commented on internal/storage/memory.go
> +	Metrics map[string]Metric
done

2024-12-01 19:31 UTC, sejo412 commented on internal/storage/metrics.go
> +type Metric struct {
унес в models

2024-12-01 19:33 UTC, sejo412 commented on cmd/agent/config.go
> +	"reflect"
думал, что будут усложнения в плане "добавьте то, не знаю что" :D

заменил рефликсию на мапу для рантайм метрик

2024-12-01 19:34 UTC, sejo412 commented on internal/config/constants.go
> +	MetricKindGauge      string = "gauge"
перенес в models

2024-12-01 19:34 UTC, sejo412 commented on internal/storage/metrics.go
> +type Storage interface {
унес в cmd

2024-12-01 19:36 UTC, sejo412 commented on cmd/server/app.go
> +	if r.Method == http.MethodGet {
не вижу принципиальной разницы - все-равно основной хендлер вызывать из функции. но втащил в роутер и убрал проверку на метод

2024-12-01 19:38 UTC, sejo412 commented on internal/config/errors.go
> +package config
и это в модели утащил

2024-12-01 19:38 UTC, sejo412 commented on cmd/agent/app.go
> +		ch <- fmt.Sprint(err)
логично. добавил

2024-12-01 19:41 UTC, sejo412 commented
> Большое количество логики в main-packages, рекомендую пересмотреть структуру приложения и добавить сервисные слои, инкапсулирующие бизнес-логику.

добавил слой app

2024-12-02 15:10 UTC, merged